language: ruby
rvm:
  - 2.0.0
env:
  global:
  - USER="Avni-Sharma"
  - EMAIL="16avnisharma@mail.com"
  - REPO="docs-test"
  - FILES="./tmp/manifests/"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  # - secure: "put travis gem output here => http://docs.travis-ci.com/user/encryption-keys/"

# deploy:
#   github_token: $GITHUB_TOKEN
script:
  echo GITHUB_TOKEN=my_github_token | travis encrypt --add 
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${GITHUB_TOKEN}@${GH_REPO}" master > /dev/null 2>&1